Repository atlp-rwanda/runners-bn-backend, pull requests merged in 2021-01, with the labels that each got.

#8 feat(setting roles): setting up roles
  .eslintrc.json
  package-lock.json
  package.json
  src/controllers/index.js
  src/controllers/user.js
  src/database/migrations/20201217215823-modify_users_add_new_fields.js
  src/database/migrations/20210102093937-create-user.js
  src/database/models/user.js
  src/database/seeders/20201217223041-demo-user.js
  src/helpers/joiResponse.js
  src/helpers/manager.js
  src/helpers/roles.js
  src/helpers/sendResponse.js
  src/helpers/statusCode.js
  src/middlewares/auth.js
  src/middlewares/index.js
  src/middlewares/joiValidator.js
  src/routes/index.js
  src/routes/userRoutes.js
  src/routes/welcomeRoute.js
  src/services/userServices.js
  src/tests/index.test.js
  src/tests/mockdata.js
  src/tests/user.test.js
Labels: feature, ready for review

#9 feat(reset password): resets password
  .env.example
  .nycrc
  package-lock.json
  package.json
  src/controllers/user.js
  src/database/migrations/20210102093937-create-user.js
  src/database/models/user.js
  src/database/seeders/20201217223041-demo-user.js
  src/helpers/actions.js
  src/helpers/generateToken.js
  src/helpers/mailer/sendMailer.js
  src/helpers/mailer/templates/index.js
  src/helpers/mailer/templates/reset.password.js
  src/helpers/verifyToken.js
  src/middlewares/auth.js
  src/middlewares/joiValidator.js
  src/routes/userRoutes.js
  src/services/userServices.js
  src/tests/mockdata.js
  src/tests/user.test.js
Labels: feature, ready for review

#14 bg(userRoute): Fixes userRoutes
  .nycrc
  package-lock.json
  package.json
  src/controllers/userController.js
  src/helpers/mailer/sendMailer.js
  src/middlewares/joiValidator.js
  src/routes/userRoutes.js
  src/tests/user.test.js
Labels: bug, ready for review

#13 feature(signup and signin): signin using passport
  .nycrc
  package-lock.json
  package.json
  src/config/passport.js
  src/config/swaggerDoc.js
  src/controllers/userController.js
  src/database/models/index.js
  src/database/models/user.js
  src/helpers/generatePassword.js
  src/helpers/generateToken.js
  src/helpers/sendResponse.js
  src/index.js
  src/middlewares/joiValidator.js
  src/middlewares/passportCheck.js
  src/routes/userRoutes.js
  src/routes/welcomeRoute.js
  src/services/userServices.js
  src/tests/mockdata.js
  src/tests/user.test.js
Labels: feature
