Repository atlp-rwanda/runners-bn-backend, pull requests merged in 2021-02, with the labels that each got.

#12 feat(trip requests): requests trips
  package-lock.json
  package.json
  src/controllers/tripController.js
  src/database/migrations/20210120044315-create-location.js
  src/database/migrations/20210120044959-create-trip.js
  src/database/models/location.js
  src/database/models/trip.js
  src/database/models/user.js
  src/database/seeders/20201217223041-demo-user.js
  src/database/seeders/20210120072231-demo-location.js
  src/middlewares/joiValidator.js
  src/routes/index.js
  src/routes/tripRoutes.js
  src/services/tripServices.js
  src/services/userServices.js
  src/tests/mockdata.js
  src/tests/trip.test.js
Labels: feature, ready for review

#16 feat(trip comments): comments on trips
  src/controllers/commentController.js
  src/database/migrations/20210102093937-create-user.js
  src/database/migrations/20210128151650-create-comment.js
  src/database/models/comment.js
  src/database/models/location.js
  src/database/models/user.js
  src/middlewares/isAllowed.js
  src/middlewares/isValidTrip.js
  src/middlewares/joiValidator.js
  src/routes/tripRoutes.js
  src/services/commentServices.js
  src/services/tripServices.js
  src/tests/mockdata.js
  src/tests/trip.test.js
Labels: feature, ready for review

#17 Ft accommodation 176153390
  package-lock.json
  package.json
  src/config/cloudinary.js
  src/config/multer.js
  src/controllers/accommodationController.js
  src/database/migrations/20210130083529-create-accommodation.js
  src/database/models/accommodation.js
  src/database/models/location.js
  src/database/seeders/20201217223041-demo-user.js
  src/helpers/generateToken.js
  src/helpers/sequelizeErrorHandler.js
  src/middlewares/isAllowed.js
  src/middlewares/joiValidator.js
  src/routes/accommodationRoutes.js
  src/routes/index.js
  src/routes/userRoutes.js
  src/services/accommodationService.js
  src/services/locationServices.js
  src/tests/accommodation.test.js
  src/tests/mockdata.js
  src/tests/testFile/m-blog-2.jpg
  src/tests/testFile/robot.jpg
Labels: ready for review

#15 bg(coveralls): Fix coveralls
  .codeclimate.yml
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
Labels: bug, ready for review

#19 feat(notification): notifications to users
  .nycrc
  package-lock.json
  package.json
  public/index.html
  src/controllers/notificationController.js
  src/controllers/userController.js
  src/database/migrations/20210102093937-create-user.js
  src/database/migrations/20210211022857-create-notification.js
  src/database/models/comment.js
  src/database/models/notification.js
  src/database/models/trip.js
  src/database/models/user.js
  src/database/seeders/20201217223041-demo-user.js
  src/helpers/EventEmitters/eventEmitter.js
  src/helpers/EventEmitters/eventListener.js
  src/helpers/actions.js
  src/helpers/generateToken.js
  src/helpers/mailer/templates/index.js
  src/helpers/mailer/templates/notification.email.js
  src/helpers/notifications/index.js
  src/helpers/sockets.js
  src/index.js
  src/middlewares/auth.js
  src/routes/accommodationRoutes.js
  src/routes/index.js
  src/routes/notificationRoute.js
  src/routes/tripRoutes.js
  src/routes/userRoutes.js
  src/services/notificationServices.js
  src/tests/index.test.js
  src/tests/mockdata.js
  src/tests/notifications.test.js
  src/tests/trip.test.js
  src/tests/user.test.js
Labels: feature, ready for review

#21 feature(room): CRUD Rooms in accommodation
  src/controllers/roomController.js
  src/database/migrations/20210216120317-create-room.js
  src/database/models/accommodation.js
  src/database/models/room.js
  src/middlewares/findAccommodation.js
  src/middlewares/joiValidator.js
  src/routes/index.js
  src/routes/roomRoutes.js
  src/services/roomServices.js
  src/tests/accommodation.test.js
  src/tests/mockdata.js
  src/tests/room.test.js
Labels: feature, ready for review
